import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { isCashierItemLocked, isCashierOrderLocked, CORRECTION_WINDOW_MS } from "../src/lib/cashier-corrections";
const now = Date.parse("2026-09-21T12:00:00Z");
const stamp = (age: number) => new Date(now - age);
const ticket = { status: "confirmed", createdAt: stamp(900_000), confirmedAt: stamp(60_000) };
const item = { createdAt: stamp(900_000), stationStatus: "pending", removed: false };
assert.equal(isCashierItemLocked(item, ticket, now), false, "held time does not consume send window");
assert.equal(isCashierItemLocked({ ...item, stationStatus: "accepted" }, ticket, now), false);
assert.equal(isCashierItemLocked({ ...item, stationStatus: "done" }, ticket, now), true);
const old = { ...ticket, confirmedAt: stamp(CORRECTION_WINDOW_MS) };
assert.equal(isCashierItemLocked(item, old, now - 1), false, "9:59.999 still editable");
assert.equal(isCashierItemLocked(item, old, now), true, "10:00 locks");
assert.equal(isCashierItemLocked(item, { ...ticket, confirmedAt: null }, now), false, "held orders remain editable");
const addition = { ...item, createdAt: stamp(1000) };
assert.equal(isCashierItemLocked(addition, old, now), false, "new line has its own window");
assert.equal(isCashierOrderLocked({ ...old, items: [item, addition] }, now), true, "can't cancel old dish with new addition");
assert.equal(isCashierOrderLocked({ ...ticket, items: [{ ...item, stationStatus: "done" }] }, now), true);
assert.equal(isCashierOrderLocked({ ...ticket, items: [{ ...item, stationStatus: "done", removed: true }, addition] }, now), false);
assert.equal(isCashierItemLocked(item, { ...old, printedAt: stamp(1) }, now), true, "printing does not restart clock");
assert.equal(isCashierItemLocked(item, { ...ticket, status: "closed" }, now), true);
const cashier = readFileSync("src/components/rms/CashierDashboard.tsx", "utf8");
assert.match(cashier, /editTarget && canKeepEditing/);
assert.match(cashier, /setInterval\(\(\) => setNowTick\(Date.now\(\)\), 1000\)/);
assert.match(cashier, /onClick=\{\(\) => markPrinted\(t\)\}/);
for (const route of ["src/app/api/tickets/route.ts", "src/app/api/tickets/items/route.ts"]) {
  const source = readFileSync(route, "utf8");
  assert.match(source, /actorRole === "cashier"/);
  assert.match(source, /for\("update"\)/);
  assert.match(source, /CORRECTION_LOCK_MESSAGE/);
  assert.match(source, /status: 409/);
}
console.log("✓ Cashier corrections: Done and exact 10-minute boundary, held orders, additions, live editor and API guards");
